[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pygpt-net"
version = "2.0.77"
description = "Desktop AI Assistant powered by GPT-4, GPT-4V, GPT-3, Whisper, TTS and DALL-E 3 with chatbot, assistant, text completion, vision and image generation, real-time internet access, commands and code execution, files upload and download and more"
readme = "README.md"
authors = [{ name = "Marcin SzczygliÅ„ski", email = "info@pygpt.net" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["py_gpt", "py-gpt", "pygpt", "desktop", "app", "gpt", "gpt4", "gpt4-v", "gpt3", "gpt-4", "gpt-4V", "gpt-3", "tts", "whisper", "vision", "chatgpt", "dall-e", "chat",
    "chatbot", "assistant", "text completion", "image generation", "ai", "api", "openai", "api key", "memory", "history",
    "presets", "ui", "qt", "pyside"]
dependencies = [
    'azure-cognitiveservices-speech>=1.27.0',
    'beautifulsoup4>=4.12.2',
    'docker>=7.0.0',
    'langchain>=0.0.345',
    'langchain-experimental>=0.0.44',
    'Markdown>=3.5.1',
    'openai>=1.3.7',
    'opencv-python>=4.8.1.78',
    'packaging>=23.0',
    'PyAudio>=0.2.14',
    'pygame>=2.5.2',
    'pyinstaller>=5.9.0',
    'PySide6>=6.4.2',
    'PySide6-Addons>=6.4.2',
    'PySide6-Essentials>=6.4.2',
    'qt-material>=2.14',
    'SpeechRecognition>=3.10.0',
    'show-in-file-manager>=1.1.4',
    'SQLAlchemy>=2.0.23',
    'tiktoken>=0.3.3',
    'wikipedia>=1.4.0',
]
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/szczyglis-dev/py-gpt"

[project.scripts]
pygpt = "pygpt_net.app:run"
