[tool.poetry]
name = "pygpt-net"
version = "2.3.0"
description = "Desktop AI Assistant powered by GPT-4, GPT-4o, GPT-4V, GPT-3.5, DALL-E 3, Llama 3, Mistral, Gemini, Claude, Langchain LLMs, Llama-index, Whisper with chatbot, assistant, text completion, vision and image generation, internet access, chat with files, commands and code execution, file upload and download, and more."
authors = ["Marcin Szczyglinski <info@pygpt.net>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/szczyglis-dev/py-gpt"
repository = "https://github.com/szczyglis-dev/py-gpt"
documentation = "https://pygpt.readthedocs.io/"
keywords = ["py_gpt", "py-gpt", "pygpt", "desktop", "app", "gpt", "gpt4", "gpt4-o", "gpt4-v", "gpt3.5", "gpt-4", "gpt-4V", "gpt-3.5", "llama3", "mistral", "gemini", "claude", "tts", "whisper", "vision", "chatgpt", "dall-e", "chat",
    "chatbot", "assistant", "text completion", "image generation", "ai", "api", "openai", "api key", "langchain", "llama-index", "presets", "ui", "qt", "pyside"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Utilities",
]
packages = [
    { from = "src", include = "pygpt_net" },
]
include = [
	"CHANGELOG.md",
	"icon.png",
	"README.md",
]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
beautifulsoup4 = "^4.12.3"
chromadb = "^0.4.23"
croniter = "^2.0.1"
docker = "^7.0.0"
docx2txt = "^0.8"
EbookLib = "^0.18"
langchain = "^0.2.14"
langchain-community = "^0.2.12"
langchain-experimental = "^0.0.64"
langchain-openai = "^0.1.22"
llama-index = "^0.10.65"
llama-index-core = "0.10.67"
llama-index-embeddings-azure-openai = "^0.1.6"
llama-index-embeddings-openai = "^0.1.6"
llama-index-embeddings-ollama = "^0.2.0"
llama-index-llms-anthropic = "^0.1.17"
llama-index-llms-openai = "0.1.29"
llama-index-llms-azure-openai = "^0.1.10"
llama-index-llms-gemini = "^0.2.0"
llama-index-llms-ollama = "^0.2.2"
llama-index-vector-stores-chroma = "^0.1.4"
llama-index-vector-stores-elasticsearch = "^0.1.4"
llama-index-vector-stores-pinecone = "^0.1.3"
llama-index-vector-stores-redis = "^0.1.2"
llama-index-readers-chatgpt-plugin = "^0.1.3"
llama-index-readers-database = "^0.1.4"
llama-index-readers-file = "^0.1.33"
llama-index-readers-github = "^0.1.9"
llama-index-readers-google = "^0.2.11"
llama-index-readers-microsoft-onedrive = "^0.1.9"
llama-index-readers-twitter = "^0.1.3"
llama-index-readers-web = "^0.1.23"
Markdown = "^3.7"
nbconvert = "^7.16.1"
openai = ">=1.41.0,<1.50.0"
opencv-python = "^4.9.0.80"
packaging = "^23.2"
pandas = "^2.2.0"
pillow = "^10.2.0"
pinecone-client = "^3.1.0"
PyAudio = "^0.2.14"
Pygments = "^2.18.0"
pydub = "^0.25.1"
pygame = "^2.5.2"
pypdf = "^4.0.2"
pyserial = "^3.5"
PySide6 = "6.4.2"
PySide6-Addons = "6.4.2"
PySide6-Essentials = "6.4.2"
redis = "^5.0.1"
qt-material = "^2.14"
SpeechRecognition = "^3.10.1"
show-in-file-manager = "^1.1.4"
SQLAlchemy = "^2.0.27"
tiktoken = "^0.7.0"
wikipedia = "^1.4.0"
youtube-transcript-api = "^0.6.2"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^6.4.0"
pytest = "^7.4.3"

[tool.poetry.scripts]
pygpt = 'pygpt_net.app:run'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
